# Generated by Django 5.1.3 on 2024-11-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="product_category",
            fields=[
                (
                    "cat_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "cat_image_url",
                    models.URLField(blank=True, max_length=2083, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="seller",
            fields=[
                (
                    "seller_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("store_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="shipping_company",
            fields=[
                (
                    "shipping_company_ID",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("shipping_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="status",
            fields=[
                (
                    "status_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("status_desc", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "prod_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sales", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "prod_image_url",
                    models.URLField(blank=True, max_length=2083, null=True),
                ),
                (
                    "cat_id",
                    models.ForeignKey(
                        db_column="cat_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product_category",
                    ),
                ),
                (
                    "seller_id",
                    models.ForeignKey(
                        db_column="seller_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.SmallIntegerField()),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prod_id",
                    models.ForeignKey(
                        db_column="prod_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="seller_address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("additional", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seller_id",
                    models.OneToOneField(
                        db_column="seller_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user_payment",
            fields=[
                (
                    "payment_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("payment_method", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("account_no", models.CharField(max_length=255, unique=True)),
                ("expiry", models.CharField(max_length=5)),
                ("cvv", models.CharField(max_length=3)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user_address",
            fields=[
                (
                    "address_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("address_line_1", models.CharField(max_length=255)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("additional", models.CharField(blank=True, max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prod_id",
                    models.ForeignKey(
                        db_column="prod_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prod_id",
                    models.ForeignKey(
                        db_column="prod_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.BigIntegerField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prod_id",
                    models.ForeignKey(
                        db_column="prod_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
                (
                    "shipping_company_ID",
                    models.ForeignKey(
                        db_column="shipping_company_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.shipping_company",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        db_column="status_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.status",
                    ),
                ),
                (
                    "address_id",
                    models.ForeignKey(
                        db_column="address_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.user_address",
                    ),
                ),
                (
                    "payment_id",
                    models.ForeignKey(
                        db_column="payment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.user_payment",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.users",
                    ),
                ),
            ],
            options={
                "unique_together": {("order_id", "prod_id")},
            },
        ),
    ]
